---
- name: OpenVPN | dnsmasq | Generate dnsmasq configuration file
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name:  OpenVPN | dnsmasq | sytemd - Make override directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/systemd/system/dnsmasq.service.d"

- name:  OpenVPN | dnsmasq | systemd - Create configuration override file
  template:
    src: etc_systemd_system_dnsmasq.service.d_override.conf.j2
    dest: /etc/systemd/system/dnsmasq.service.d/override.conf
