---
- name: OpenVPN | Harden Kernel | Disable various kernel modules
  kernel_blacklist:
    name: "{{ item }}"
    state: present
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - dccp
    - sctp
    - rds
    - tipc
    - firewire-core
    - usb-storage
    - net-pf-31
    - bluetooth
