---
- name: OpenVPN | Harden Services | cron.allow
  copy:
    content: "root"
    dest: "/etc/cron.allow"
    owner: root
    group: root
    mode: 0644

# Note aide package on debian requires parts of exim, so can't uninstall it. just disable.
- name: OpenVPN | Harden Services | Disable mail services
  service:
    name: "{{ item }}"
    enabled: false
  with_items:
    - exim4
    - postfix
