---
- name: OpenVPN | Install | Set Distro/Version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    #- "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    #- "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    #- "../vars/default.yml"

- include: packages.yml
- include: pki.yml
- include: openvpn.yml
- include: dns.yml
- include: harden_sysctl.yml
- include: harden_umask.yml
- include: harden_services.yml
- include: harden_kernel.yml
- include: harden_misc.yml
- include: harden_auditd.yml

- include: firewall.yml
- include: harden_password.yml
- include: harden_users.yml
- include: harden_sshd.yml
- include: harden_aide.yml

- name: OpenVPN | Install | Clear bash history
  shell: cat /dev/null > ~/.bash_history && history -c
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: true
