- name: Revoke client access
# ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('openvpn-vpn') }}"

  roles:
    - revoke_client
